// CuraNav: synthetic hospital mock data
// 24 records, evenly covering 6 conditions x 6 cities (Chandigarh, Mohali, Panchkula, Ludhiana, Jalandhar, Delhi)
// All records are synthetic/demo data — surface source_type & verification_status badges wherever shown.

export type SourceType = 'official' | 'public' | 'synthetic';
export type VerificationStatus = 'verified' | 'pending' | 'simulated';
export type ReviewStatus = 'pending' | 'approved' | 'rejected';

export interface Hospital {
  hospitalId: string;
  name: string;
  city: string;
  state: string;
  pincode: string;
  address: string;
  latitude: number;
  longitude: number;
  specialties: string[];
  procedures: string[];
  costMin: number;
  costMax: number;
  currency: string;
  facilities: string[];
  accreditation: string[];
  pmjayEmpanelled: boolean;
  annualProcedureVolume: number;
  outcomeMetric: string;
  icuBeds: number;
  sourceType: SourceType;
  verificationStatus: VerificationStatus;
  sourceUrl: string | null;
  lastVerified: string | null;
  lastUpdated: string;
  dataStatus: string;
  conditionTag: string;
  reviewStatus: ReviewStatus;
}

export const mockHospitals: Hospital[] = [
  {
      hospitalId: "HOSP-001",
      name: "Riverside Nephro Care",
      city: "Chandigarh",
      state: "Chandigarh",
      pincode: "160001",
      address: "12 Sector 14, Chandigarh",
      latitude: 30.7472,
      longitude: 76.7319,
      specialties: ["Nephrology"],
      procedures: ["Dialysis", "Kidney Transplant", "Nephrology Consultation"],
      costMin: 60000,
      costMax: 120000,
      currency: "INR",
      facilities: ["Dialysis", "ICU", "Blood Bank"],
      accreditation: ["NABH", "NABL"],
      pmjayEmpanelled: true,
      annualProcedureVolume: 450,
      outcomeMetric: "95% reported success rate",
      icuBeds: 8,
      sourceType: "synthetic",
      verificationStatus: "verified",
      sourceUrl: null,
      lastVerified: "2026-08-14",
      lastUpdated: "2026-09-02",
      dataStatus: "synthetic_demo_data",
      reviewStatus: "approved",
      conditionTag: "kidney disease",
  },
  {
      hospitalId: "HOSP-002",
      name: "Sukhna Kidney & Dialysis Centre",
      city: "Mohali",
      state: "Punjab",
      pincode: "160055",
      address: "90 Sector 28, Mohali",
      latitude: 30.6779,
      longitude: 76.7281,
      specialties: ["Nephrology"],
      procedures: ["Dialysis", "Kidney Transplant", "Nephrology Consultation"],
      costMin: 100000,
      costMax: 160000,
      currency: "INR",
      facilities: ["Dialysis", "ICU", "Blood Bank"],
      accreditation: ["ISO 9001"],
      pmjayEmpanelled: true,
      annualProcedureVolume: 900,
      outcomeMetric: "97% reported success rate",
      icuBeds: 24,
      sourceType: "synthetic",
      verificationStatus: "verified",
      sourceUrl: null,
      lastVerified: "2026-08-28",
      lastUpdated: "2026-09-01",
      dataStatus: "synthetic_demo_data",
      reviewStatus: "approved",
      conditionTag: "kidney disease",
  },
  {
      hospitalId: "HOSP-003",
      name: "North Renal Institute",
      city: "Panchkula",
      state: "Haryana",
      pincode: "134109",
      address: "49 Sector 6, Panchkula",
      latitude: 30.6782,
      longitude: 76.8261,
      specialties: ["Nephrology"],
      procedures: ["Dialysis", "Kidney Transplant", "Nephrology Consultation"],
      costMin: 60000,
      costMax: 100000,
      currency: "INR",
      facilities: ["Dialysis", "ICU", "Blood Bank", "MRI"],
      accreditation: ["NABH"],
      pmjayEmpanelled: true,
      annualProcedureVolume: 1100,
      outcomeMetric: "95% reported success rate",
      icuBeds: 16,
      sourceType: "synthetic",
      verificationStatus: "verified",
      sourceUrl: null,
      lastVerified: "2026-08-09",
      lastUpdated: "2026-09-02",
      dataStatus: "synthetic_demo_data",
      reviewStatus: "approved",
      conditionTag: "kidney disease",
  },
  {
      hospitalId: "HOSP-004",
      name: "Shivalik Kidney Hospital",
      city: "Ludhiana",
      state: "Punjab",
      pincode: "141001",
      address: "30 Sector 7, Ludhiana",
      latitude: 30.9062,
      longitude: 75.8902,
      specialties: ["Nephrology"],
      procedures: ["Dialysis", "Kidney Transplant", "Nephrology Consultation"],
      costMin: 100000,
      costMax: 180000,
      currency: "INR",
      facilities: ["Dialysis", "ICU", "Blood Bank"],
      accreditation: ["NABH", "NABL"],
      pmjayEmpanelled: false,
      annualProcedureVolume: 750,
      outcomeMetric: "97% reported success rate",
      icuBeds: 8,
      sourceType: "synthetic",
      verificationStatus: "pending",
      sourceUrl: null,
      lastVerified: null,
      lastUpdated: "2026-09-10",
      dataStatus: "synthetic_demo_data",
      reviewStatus: "approved",
      conditionTag: "kidney disease",
  },
  {
      hospitalId: "HOSP-005",
      name: "Heartline Cardiac Institute",
      city: "Mohali",
      state: "Punjab",
      pincode: "160055",
      address: "21 Sector 30, Mohali",
      latitude: 30.6926,
      longitude: 76.7132,
      specialties: ["Cardiology"],
      procedures: ["Angioplasty", "Bypass Surgery", "Cardiology Consultation"],
      costMin: 60000,
      costMax: 120000,
      currency: "INR",
      facilities: ["Cath Lab", "ICU", "Emergency Department", "CT scan", "Ambulance Service"],
      accreditation: [],
      pmjayEmpanelled: true,
      annualProcedureVolume: 900,
      outcomeMetric: "96% reported success rate",
      icuBeds: 30,
      sourceType: "synthetic",
      verificationStatus: "verified",
      sourceUrl: null,
      lastVerified: "2026-08-22",
      lastUpdated: "2026-09-03",
      dataStatus: "synthetic_demo_data",
      reviewStatus: "approved",
      conditionTag: "heart disease",
  },
  {
      hospitalId: "HOSP-006",
      name: "Tricity Cardiac Centre",
      city: "Panchkula",
      state: "Haryana",
      pincode: "134109",
      address: "35 Sector 5, Panchkula",
      latitude: 30.6821,
      longitude: 76.9096,
      specialties: ["Cardiology"],
      procedures: ["Angioplasty", "Bypass Surgery", "Cardiology Consultation"],
      costMin: 120000,
      costMax: 270000,
      currency: "INR",
      facilities: ["Cath Lab", "ICU", "Emergency Department", "Blood Bank"],
      accreditation: ["NABH", "NABL"],
      pmjayEmpanelled: false,
      annualProcedureVolume: 300,
      outcomeMetric: "90% reported success rate",
      icuBeds: 40,
      sourceType: "synthetic",
      verificationStatus: "simulated",
      sourceUrl: null,
      lastVerified: "2026-08-27",
      lastUpdated: "2026-09-02",
      dataStatus: "synthetic_demo_data",
      reviewStatus: "approved",
      conditionTag: "heart disease",
  },
  {
      hospitalId: "HOSP-007",
      name: "Satluj Heart Hospital",
      city: "Ludhiana",
      state: "Punjab",
      pincode: "141001",
      address: "72 Sector 35, Ludhiana",
      latitude: 30.8721,
      longitude: 75.9016,
      specialties: ["Cardiology"],
      procedures: ["Angioplasty", "Bypass Surgery", "Cardiology Consultation"],
      costMin: 120000,
      costMax: 200000,
      currency: "INR",
      facilities: ["Cath Lab", "ICU", "Emergency Department"],
      accreditation: ["NABH", "NABL"],
      pmjayEmpanelled: false,
      annualProcedureVolume: 1500,
      outcomeMetric: "90% reported success rate",
      icuBeds: 20,
      sourceType: "synthetic",
      verificationStatus: "verified",
      sourceUrl: null,
      lastVerified: "2026-08-09",
      lastUpdated: "2026-09-05",
      dataStatus: "synthetic_demo_data",
      reviewStatus: "approved",
      conditionTag: "heart disease",
  },
  {
      hospitalId: "HOSP-008",
      name: "Ivory Cardiac Care",
      city: "Jalandhar",
      state: "Punjab",
      pincode: "144001",
      address: "20 Sector 41, Jalandhar",
      latitude: 31.3023,
      longitude: 75.5847,
      specialties: ["Cardiology"],
      procedures: ["Angioplasty", "Bypass Surgery", "Cardiology Consultation"],
      costMin: 100000,
      costMax: 200000,
      currency: "INR",
      facilities: ["Cath Lab", "ICU", "Emergency Department"],
      accreditation: [],
      pmjayEmpanelled: true,
      annualProcedureVolume: 1500,
      outcomeMetric: "88% reported success rate",
      icuBeds: 12,
      sourceType: "synthetic",
      verificationStatus: "pending",
      sourceUrl: null,
      lastVerified: null,
      lastUpdated: "2026-09-02",
      dataStatus: "synthetic_demo_data",
      reviewStatus: "approved",
      conditionTag: "heart disease",
  },
  {
      hospitalId: "HOSP-009",
      name: "Hopewell Cancer Centre",
      city: "Panchkula",
      state: "Haryana",
      pincode: "134109",
      address: "83 Sector 22, Panchkula",
      latitude: 30.6602,
      longitude: 76.8786,
      specialties: ["Oncology"],
      procedures: ["Chemotherapy", "Radiation Therapy", "Oncology Consultation"],
      costMin: 100000,
      costMax: 140000,
      currency: "INR",
      facilities: ["Oncology Unit", "ICU", "Blood Bank", "MRI", "Robotic Surgery"],
      accreditation: ["ISO 9001"],
      pmjayEmpanelled: true,
      annualProcedureVolume: 900,
      outcomeMetric: "95% reported success rate",
      icuBeds: 20,
      sourceType: "synthetic",
      verificationStatus: "verified",
      sourceUrl: null,
      lastVerified: "2026-08-28",
      lastUpdated: "2026-09-01",
      dataStatus: "synthetic_demo_data",
      reviewStatus: "approved",
      conditionTag: "cancer",
  },
  {
      hospitalId: "HOSP-010",
      name: "Beas Oncology Institute",
      city: "Ludhiana",
      state: "Punjab",
      pincode: "141001",
      address: "20 Sector 24, Ludhiana",
      latitude: 30.8622,
      longitude: 75.8508,
      specialties: ["Oncology"],
      procedures: ["Chemotherapy", "Radiation Therapy", "Oncology Consultation"],
      costMin: 80000,
      costMax: 120000,
      currency: "INR",
      facilities: ["Oncology Unit", "ICU", "Blood Bank", "Ambulance Service", "CT scan"],
      accreditation: [],
      pmjayEmpanelled: false,
      annualProcedureVolume: 600,
      outcomeMetric: "95% reported success rate",
      icuBeds: 40,
      sourceType: "synthetic",
      verificationStatus: "verified",
      sourceUrl: null,
      lastVerified: "2026-08-04",
      lastUpdated: "2026-09-10",
      dataStatus: "synthetic_demo_data",
      reviewStatus: "approved",
      conditionTag: "cancer",
  },
  {
      hospitalId: "HOSP-011",
      name: "Amaltas Cancer Hospital",
      city: "Jalandhar",
      state: "Punjab",
      pincode: "144001",
      address: "8 Sector 16, Jalandhar",
      latitude: 31.3523,
      longitude: 75.5801,
      specialties: ["Oncology"],
      procedures: ["Chemotherapy", "Radiation Therapy", "Oncology Consultation"],
      costMin: 100000,
      costMax: 140000,
      currency: "INR",
      facilities: ["Oncology Unit", "ICU", "Blood Bank"],
      accreditation: [],
      pmjayEmpanelled: true,
      annualProcedureVolume: 1100,
      outcomeMetric: "97% reported success rate",
      icuBeds: 8,
      sourceType: "synthetic",
      verificationStatus: "verified",
      sourceUrl: null,
      lastVerified: "2026-08-26",
      lastUpdated: "2026-09-10",
      dataStatus: "synthetic_demo_data",
      reviewStatus: "approved",
      conditionTag: "cancer",
  },
  {
      hospitalId: "HOSP-012",
      name: "Northgate Oncology Care",
      city: "Delhi",
      state: "Delhi",
      pincode: "110001",
      address: "68 Sector 39, Delhi",
      latitude: 28.7419,
      longitude: 77.1472,
      specialties: ["Oncology"],
      procedures: ["Chemotherapy", "Radiation Therapy", "Oncology Consultation"],
      costMin: 30000,
      costMax: 130000,
      currency: "INR",
      facilities: ["Oncology Unit", "ICU", "Blood Bank", "CT scan", "Robotic Surgery"],
      accreditation: ["NABH"],
      pmjayEmpanelled: false,
      annualProcedureVolume: 600,
      outcomeMetric: "90% reported success rate",
      icuBeds: 24,
      sourceType: "synthetic",
      verificationStatus: "simulated",
      sourceUrl: null,
      lastVerified: "2026-08-22",
      lastUpdated: "2026-09-16",
      dataStatus: "synthetic_demo_data",
      reviewStatus: "approved",
      conditionTag: "cancer",
  },
  {
      hospitalId: "HOSP-013",
      name: "Ortho Plus Hospital",
      city: "Ludhiana",
      state: "Punjab",
      pincode: "141001",
      address: "32 Sector 15, Ludhiana",
      latitude: 30.8933,
      longitude: 75.8285,
      specialties: ["Orthopaedics"],
      procedures: ["Joint Replacement", "Fracture Repair", "Orthopaedic Consultation"],
      costMin: 100000,
      costMax: 160000,
      currency: "INR",
      facilities: ["MRI", "CT scan", "Emergency Department"],
      accreditation: [],
      pmjayEmpanelled: true,
      annualProcedureVolume: 1100,
      outcomeMetric: "94% reported success rate",
      icuBeds: 30,
      sourceType: "synthetic",
      verificationStatus: "verified",
      sourceUrl: null,
      lastVerified: "2026-08-17",
      lastUpdated: "2026-09-15",
      dataStatus: "synthetic_demo_data",
      reviewStatus: "approved",
      conditionTag: "orthopaedic conditions",
  },
  {
      hospitalId: "HOSP-014",
      name: "Boneline Orthopaedic Centre",
      city: "Jalandhar",
      state: "Punjab",
      pincode: "144001",
      address: "66 Sector 16, Jalandhar",
      latitude: 31.2824,
      longitude: 75.5283,
      specialties: ["Orthopaedics"],
      procedures: ["Joint Replacement", "Fracture Repair", "Orthopaedic Consultation"],
      costMin: 100000,
      costMax: 160000,
      currency: "INR",
      facilities: ["MRI", "CT scan", "Emergency Department"],
      accreditation: ["NABH", "NABL"],
      pmjayEmpanelled: true,
      annualProcedureVolume: 300,
      outcomeMetric: "90% reported success rate",
      icuBeds: 30,
      sourceType: "synthetic",
      verificationStatus: "verified",
      sourceUrl: null,
      lastVerified: "2026-08-03",
      lastUpdated: "2026-09-02",
      dataStatus: "synthetic_demo_data",
      reviewStatus: "approved",
      conditionTag: "orthopaedic conditions",
  },
  {
      hospitalId: "HOSP-015",
      name: "Ridge Joint & Trauma Care",
      city: "Delhi",
      state: "Delhi",
      pincode: "110001",
      address: "55 Sector 27, Delhi",
      latitude: 28.6819,
      longitude: 77.101,
      specialties: ["Orthopaedics"],
      procedures: ["Joint Replacement", "Fracture Repair", "Orthopaedic Consultation"],
      costMin: 100000,
      costMax: 160000,
      currency: "INR",
      facilities: ["MRI", "CT scan", "Emergency Department", "Blood Bank", "Robotic Surgery"],
      accreditation: ["ISO 9001"],
      pmjayEmpanelled: true,
      annualProcedureVolume: 1240,
      outcomeMetric: "90% reported success rate",
      icuBeds: 20,
      sourceType: "synthetic",
      verificationStatus: "verified",
      sourceUrl: null,
      lastVerified: "2026-08-04",
      lastUpdated: "2026-09-04",
      dataStatus: "synthetic_demo_data",
      reviewStatus: "approved",
      conditionTag: "orthopaedic conditions",
  },
  {
      hospitalId: "HOSP-016",
      name: "Sirhind Ortho Institute",
      city: "Chandigarh",
      state: "Chandigarh",
      pincode: "160001",
      address: "69 Sector 29, Chandigarh",
      latitude: 30.73,
      longitude: 76.8023,
      specialties: ["Orthopaedics"],
      procedures: ["Joint Replacement", "Fracture Repair", "Orthopaedic Consultation"],
      costMin: 120000,
      costMax: 160000,
      currency: "INR",
      facilities: ["MRI", "CT scan", "Emergency Department"],
      accreditation: ["NABH"],
      pmjayEmpanelled: true,
      annualProcedureVolume: 450,
      outcomeMetric: "90% reported success rate",
      icuBeds: 16,
      sourceType: "synthetic",
      verificationStatus: "pending",
      sourceUrl: null,
      lastVerified: null,
      lastUpdated: "2026-09-07",
      dataStatus: "synthetic_demo_data",
      reviewStatus: "approved",
      conditionTag: "orthopaedic conditions",
  },
  {
      hospitalId: "HOSP-017",
      name: "Motherhood Maternity Hospital",
      city: "Jalandhar",
      state: "Punjab",
      pincode: "144001",
      address: "12 Sector 49, Jalandhar",
      latitude: 31.29,
      longitude: 75.5445,
      specialties: ["Obstetrics and Gynaecology"],
      procedures: ["Normal Delivery", "C-Section", "Prenatal Care"],
      costMin: 80000,
      costMax: 140000,
      currency: "INR",
      facilities: ["NICU", "ICU", "Blood Bank"],
      accreditation: ["NABH"],
      pmjayEmpanelled: true,
      annualProcedureVolume: 450,
      outcomeMetric: "88% reported success rate",
      icuBeds: 40,
      sourceType: "synthetic",
      verificationStatus: "verified",
      sourceUrl: null,
      lastVerified: "2026-08-21",
      lastUpdated: "2026-09-18",
      dataStatus: "synthetic_demo_data",
      reviewStatus: "approved",
      conditionTag: "maternity / pregnancy",
  },
  {
      hospitalId: "HOSP-018",
      name: "New Life Women's Hospital",
      city: "Delhi",
      state: "Delhi",
      pincode: "110001",
      address: "37 Sector 28, Delhi",
      latitude: 28.739,
      longitude: 77.0691,
      specialties: ["Obstetrics and Gynaecology"],
      procedures: ["Normal Delivery", "C-Section", "Prenatal Care"],
      costMin: 80000,
      costMax: 180000,
      currency: "INR",
      facilities: ["NICU", "ICU", "Blood Bank"],
      accreditation: ["NABH", "NABL"],
      pmjayEmpanelled: false,
      annualProcedureVolume: 600,
      outcomeMetric: "94% reported success rate",
      icuBeds: 8,
      sourceType: "synthetic",
      verificationStatus: "simulated",
      sourceUrl: null,
      lastVerified: "2026-08-01",
      lastUpdated: "2026-09-13",
      dataStatus: "synthetic_demo_data",
      reviewStatus: "approved",
      conditionTag: "maternity / pregnancy",
  },
  {
      hospitalId: "HOSP-019",
      name: "Cradle Care Maternity Centre",
      city: "Chandigarh",
      state: "Chandigarh",
      pincode: "160001",
      address: "41 Sector 4, Chandigarh",
      latitude: 30.753,
      longitude: 76.8025,
      specialties: ["Obstetrics and Gynaecology"],
      procedures: ["Normal Delivery", "C-Section", "Prenatal Care"],
      costMin: 100000,
      costMax: 200000,
      currency: "INR",
      facilities: ["NICU", "ICU", "Blood Bank"],
      accreditation: ["NABH", "NABL"],
      pmjayEmpanelled: true,
      annualProcedureVolume: 300,
      outcomeMetric: "95% reported success rate",
      icuBeds: 12,
      sourceType: "synthetic",
      verificationStatus: "verified",
      sourceUrl: null,
      lastVerified: "2026-08-24",
      lastUpdated: "2026-09-18",
      dataStatus: "synthetic_demo_data",
      reviewStatus: "approved",
      conditionTag: "maternity / pregnancy",
  },
  {
      hospitalId: "HOSP-020",
      name: "Sundial Mother & Child Hospital",
      city: "Mohali",
      state: "Punjab",
      pincode: "160055",
      address: "87 Sector 16, Mohali",
      latitude: 30.6596,
      longitude: 76.7156,
      specialties: ["Obstetrics and Gynaecology"],
      procedures: ["Normal Delivery", "C-Section", "Prenatal Care"],
      costMin: 100000,
      costMax: 160000,
      currency: "INR",
      facilities: ["NICU", "ICU", "Blood Bank"],
      accreditation: ["NABH"],
      pmjayEmpanelled: false,
      annualProcedureVolume: 600,
      outcomeMetric: "88% reported success rate",
      icuBeds: 8,
      sourceType: "synthetic",
      verificationStatus: "pending",
      sourceUrl: null,
      lastVerified: null,
      lastUpdated: "2026-09-20",
      dataStatus: "synthetic_demo_data",
      reviewStatus: "approved",
      conditionTag: "maternity / pregnancy",
  },
  {
      hospitalId: "HOSP-021",
      name: "Rapid Response General Hospital",
      city: "Delhi",
      state: "Delhi",
      pincode: "110001",
      address: "34 Sector 26, Delhi",
      latitude: 28.6945,
      longitude: 77.1467,
      specialties: ["Emergency Medicine"],
      procedures: ["Trauma Care", "Emergency Surgery", "Critical Care"],
      costMin: 100000,
      costMax: 160000,
      currency: "INR",
      facilities: ["Emergency Department", "ICU", "CT scan"],
      accreditation: ["NABH"],
      pmjayEmpanelled: false,
      annualProcedureVolume: 1100,
      outcomeMetric: "92% reported success rate",
      icuBeds: 20,
      sourceType: "synthetic",
      verificationStatus: "verified",
      sourceUrl: null,
      lastVerified: "2026-08-07",
      lastUpdated: "2026-09-11",
      dataStatus: "synthetic_demo_data",
      reviewStatus: "approved",
      conditionTag: "emergency care",
  },
  {
      hospitalId: "HOSP-022",
      name: "CityCare Emergency Hospital",
      city: "Chandigarh",
      state: "Chandigarh",
      pincode: "160001",
      address: "45 Sector 5, Chandigarh",
      latitude: 30.6964,
      longitude: 76.794,
      specialties: ["Emergency Medicine"],
      procedures: ["Trauma Care", "Emergency Surgery", "Critical Care"],
      costMin: 80000,
      costMax: 160000,
      currency: "INR",
      facilities: ["Emergency Department", "ICU", "CT scan", "Robotic Surgery"],
      accreditation: ["NABH"],
      pmjayEmpanelled: true,
      annualProcedureVolume: 450,
      outcomeMetric: "88% reported success rate",
      icuBeds: 24,
      sourceType: "synthetic",
      verificationStatus: "verified",
      sourceUrl: null,
      lastVerified: "2026-08-18",
      lastUpdated: "2026-09-07",
      dataStatus: "synthetic_demo_data",
      reviewStatus: "approved",
      conditionTag: "emergency care",
  },
  {
      hospitalId: "HOSP-023",
      name: "Trident Multispecialty Hospital",
      city: "Mohali",
      state: "Punjab",
      pincode: "160055",
      address: "18 Sector 17, Mohali",
      latitude: 30.7425,
      longitude: 76.7049,
      specialties: ["Emergency Medicine"],
      procedures: ["Trauma Care", "Emergency Surgery", "Critical Care"],
      costMin: 50000,
      costMax: 150000,
      currency: "INR",
      facilities: ["Emergency Department", "ICU", "CT scan", "MRI"],
      accreditation: [],
      pmjayEmpanelled: false,
      annualProcedureVolume: 300,
      outcomeMetric: "96% reported success rate",
      icuBeds: 40,
      sourceType: "synthetic",
      verificationStatus: "verified",
      sourceUrl: null,
      lastVerified: "2026-08-27",
      lastUpdated: "2026-09-18",
      dataStatus: "synthetic_demo_data",
      reviewStatus: "approved",
      conditionTag: "emergency care",
  },
  {
      hospitalId: "HOSP-024",
      name: "Grand Trunk General Hospital",
      city: "Panchkula",
      state: "Haryana",
      pincode: "134109",
      address: "7 Sector 6, Panchkula",
      latitude: 30.6557,
      longitude: 76.8213,
      specialties: ["Emergency Medicine"],
      procedures: ["Trauma Care", "Emergency Surgery", "Critical Care"],
      costMin: 100000,
      costMax: 160000,
      currency: "INR",
      facilities: ["Emergency Department", "ICU", "CT scan", "Blood Bank", "Robotic Surgery"],
      accreditation: [],
      pmjayEmpanelled: true,
      annualProcedureVolume: 1100,
      outcomeMetric: "90% reported success rate",
      icuBeds: 12,
      sourceType: "synthetic",
      verificationStatus: "simulated",
      sourceUrl: null,
      lastVerified: "2026-08-22",
      lastUpdated: "2026-09-09",
      dataStatus: "synthetic_demo_data",
      reviewStatus: "approved",
      conditionTag: "emergency care",
  },
];
