// CuraNav: Real hospital data from NHA PMJAY (hem.nha.gov.in)
// 79 records imported from CSV files on 2026-09-22
// Source: National Health Authority – Health Empanelment Module
// All hospitals are PMJAY-empanelled facilities.

export type SourceType = 'official' | 'public' | 'synthetic';
export type VerificationStatus = 'verified' | 'pending' | 'simulated';
export type ReviewStatus = 'pending' | 'approved' | 'rejected';

export interface Hospital {
  hospitalId: string;
  name: string;
  city: string | null;
  state: string | null;
  pincode: string | null;
  address: string;
  latitude: number | null;
  longitude: number | null;
  specialties: string[];
  procedures: string[];
  costMin: number | null;
  costMax: number | null;
  currency: string;
  facilities: string[];
  accreditation: string[];
  pmjayEmpanelled: boolean;
  annualProcedureVolume: number | null;
  outcomeMetric: string | null;
  icuBeds: number | null;
  sourceType: SourceType;
  verificationStatus: VerificationStatus;
  sourceUrl: string | null;
  lastVerified: string | null;
  lastUpdated: string;
  dataStatus: string;
  conditionTag: string | null;
  reviewStatus: ReviewStatus;
  phone: string | null;
  facilityType: string | null;
  dateOfEstablishment: string | null;
}

export const mockHospitals: Hospital[] = [
  {
    hospitalId: "HOSP27G26101134",
    name: "Chandranagar TR",
    city: null,
    state: null,
    pincode: null,
    address: "Vanai",
    latitude: null,
    longitude: null,
    specialties: ["Burns Management", "General Medicine", "General Surgery", "Neo-natal Care"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9284594537",
    facilityType: "Hospital",
    dateOfEstablishment: null,
  },
  {
    hospitalId: "HOSP23G25101202",
    name: "PHC UNHEL",
    city: null,
    state: null,
    pincode: null,
    address: "PHC UNHEL",
    latitude: null,
    longitude: null,
    specialties: ["Emergency Room Packages", "General Medicine", "Obstetrics & Gynaecology", "Paediatric Medical Management"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "8225005724",
    facilityType: "Hospital",
    dateOfEstablishment: "01-05-1980",
  },
  {
    hospitalId: "HOSP27G25101325",
    name: "Kelwa Mahim",
    city: null,
    state: null,
    pincode: null,
    address: "near Mahim fort , Mahim village",
    latitude: null,
    longitude: null,
    specialties: ["General Medicine"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9881064293",
    facilityType: "Hospital",
    dateOfEstablishment: null,
  },
  {
    hospitalId: "HOSP30G25101417",
    name: "Primary Health Centre Candolim",
    city: null,
    state: null,
    pincode: null,
    address: "House No. 522,Vaddy Candolim Bardez Goa",
    latitude: null,
    longitude: null,
    specialties: ["Emergency Room Packages", "General Medicine"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9372170545",
    facilityType: "Hospital",
    dateOfEstablishment: "15-08-1972",
  },
  {
    hospitalId: "HOSP23G25101487",
    name: "PHC MOHANGARH",
    city: null,
    state: null,
    pincode: null,
    address: "GOVERNMENT HOSPITAL MOHANGARH",
    latitude: null,
    longitude: null,
    specialties: ["General Medicine"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9752537177",
    facilityType: "Hospital",
    dateOfEstablishment: null,
  },
  {
    hospitalId: "HOSP23G25101745",
    name: "chinour PHC",
    city: null,
    state: null,
    pincode: null,
    address: "Chinour PHC",
    latitude: null,
    longitude: null,
    specialties: ["General Medicine"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "8319168570",
    facilityType: "Hospital",
    dateOfEstablishment: null,
  },
  {
    hospitalId: "HOSP27G26101757",
    name: "RH MANDRUP",
    city: null,
    state: null,
    pincode: null,
    address: "MANDRUP SOUTH SOLAPUR",
    latitude: null,
    longitude: null,
    specialties: ["General Medicine", "General Surgery", "Obstetrics & Gynaecology", "Orthopaedics"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "7020870098",
    facilityType: "Hospital",
    dateOfEstablishment: null,
  },
  {
    hospitalId: "HOSP6G25101888",
    name: "Poly Clinic Rohtak",
    city: null,
    state: null,
    pincode: null,
    address: "sector 3 Near Jai Krishna International School,Sonepat Road",
    latitude: null,
    longitude: null,
    specialties: ["Emergency Room Packages", "General Medicine", "Neo-natal Care", "Obstetrics & Gynaecology"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9812386086",
    facilityType: "Hospital",
    dateOfEstablishment: "01-03-2014",
  },
  {
    hospitalId: "HOSP27G25102101",
    name: "Runza TR",
    city: null,
    state: null,
    pincode: null,
    address: "Runza",
    latitude: null,
    longitude: null,
    specialties: ["General Medicine"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9764340349",
    facilityType: "Hospital",
    dateOfEstablishment: "20-09-1984",
  },
  {
    hospitalId: "HOSP23G25102179",
    name: "PHC Berchha",
    city: null,
    state: null,
    pincode: null,
    address: "PHC BERCHHA DISTRICT SHAJAPUR",
    latitude: null,
    longitude: null,
    specialties: ["General Medicine"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "7999035034",
    facilityType: "Hospital",
    dateOfEstablishment: null,
  },
  {
    hospitalId: "HOSP27G26102194",
    name: "Kathora Khurd",
    city: null,
    state: null,
    pincode: null,
    address: "At Post Kathora khu,at post kathora bk tal bhusawal dist jagaon",
    latitude: null,
    longitude: null,
    specialties: ["General Medicine", "General Surgery", "Obstetrics & Gynaecology"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "8805358291",
    facilityType: "Hospital",
    dateOfEstablishment: null,
  },
  {
    hospitalId: "HOSP27G26102305",
    name: "Dahiphal Khandare",
    city: null,
    state: null,
    pincode: null,
    address: "mantha,dahifal",
    latitude: null,
    longitude: null,
    specialties: ["Burns Management", "Emergency Room Packages", "General Medicine", "General Surgery"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9545189280",
    facilityType: "Hospital",
    dateOfEstablishment: "20-08-1984",
  },
  {
    hospitalId: "HOSP27G25102438",
    name: "PHC Shioor",
    city: null,
    state: null,
    pincode: null,
    address: "PHC Shioor, Behind Bus Stand, Shioor",
    latitude: null,
    longitude: null,
    specialties: ["General Medicine"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "7745875163",
    facilityType: "Hospital",
    dateOfEstablishment: "01-09-1998",
  },
  {
    hospitalId: "HOSP6G25102607",
    name: "PHC GHOGHRIAN",
    city: null,
    state: null,
    pincode: null,
    address: "PHC GHOGHRIAN",
    latitude: null,
    longitude: null,
    specialties: ["Emergency Room Packages", "General Medicine", "Obstetrics & Gynaecology", "Paediatric Medical Management"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "8708589823",
    facilityType: "Hospital",
    dateOfEstablishment: "01-01-1990",
  },
  {
    hospitalId: "HOSP27G25102814",
    name: "Phc Raniuncegaon",
    city: null,
    state: null,
    pincode: null,
    address: "Raniunchegaon",
    latitude: null,
    longitude: null,
    specialties: ["General Medicine"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9403493852",
    facilityType: "Hospital",
    dateOfEstablishment: null,
  },
  {
    hospitalId: "HOSP27G25103192",
    name: "PRIMARY HEALTH CENTRE",
    city: null,
    state: null,
    pincode: null,
    address: "Khasgaon",
    latitude: null,
    longitude: null,
    specialties: ["General Medicine"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "7588343340",
    facilityType: "Hospital",
    dateOfEstablishment: "08-10-2018",
  },
  {
    hospitalId: "HOSP7G25103315",
    name: "Rajiv Gandhi Super Speciality Hospital",
    city: null,
    state: null,
    pincode: null,
    address: "Rajiv Gandhi Super Specialty Hospital, Tahirpur, Delhi",
    latitude: null,
    longitude: null,
    specialties: ["Cardiology", "Cardio-Thoracic & Vascular Surgery", "General Medicine", "General Surgery"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9810228857",
    facilityType: "Hospital",
    dateOfEstablishment: "20-09-2013",
  },
  {
    hospitalId: "HOSP23G25103398",
    name: "PHC BADAWADA",
    city: null,
    state: null,
    pincode: null,
    address: "BADAWADA",
    latitude: null,
    longitude: null,
    specialties: ["General Medicine", "Obstetrics & Gynaecology"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9074356554",
    facilityType: "Hospital",
    dateOfEstablishment: null,
  },
  {
    hospitalId: "HOSP27G25103477",
    name: "phc Astagaon",
    city: null,
    state: null,
    pincode: null,
    address: "PHC Astagaon",
    latitude: null,
    longitude: null,
    specialties: ["General Medicine"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9860080472",
    facilityType: "Hospital",
    dateOfEstablishment: null,
  },
  {
    hospitalId: "HOSP27G25103541",
    name: "Rural Hospital Patan",
    city: null,
    state: null,
    pincode: null,
    address: "Rural Hospital Patan",
    latitude: null,
    longitude: null,
    specialties: ["General Medicine", "General Surgery", "Obstetrics & Gynaecology", "Orthopaedics"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "8956751830",
    facilityType: "Hospital",
    dateOfEstablishment: null,
  },
  {
    hospitalId: "HOSP27P26277430",
    name: "Relief Hospitals",
    city: null,
    state: null,
    pincode: null,
    address: "Aster Building Nine Star Grandeur Char Rasta Manor Road Palghar",
    latitude: null,
    longitude: null,
    specialties: ["Burns Management", "Cardiology", "Cardio-Thoracic & Vascular Surgery", "Emergency Room Packages"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "pending",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9181999999",
    facilityType: "Hospital",
    dateOfEstablishment: "01-03-2021",
  },
  {
    hospitalId: "HOSP12P2515874",
    name: "NIBA HOSPITAL",
    city: null,
    state: null,
    pincode: null,
    address: "Papu Nallah, Naharlagun",
    latitude: null,
    longitude: null,
    specialties: ["General Medicine", "General Surgery", "Obstetrics & Gynaecology", "Ophthalmology"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "pending",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "7628878332",
    facilityType: "Hospital",
    dateOfEstablishment: "21-12-1999",
  },
  {
    hospitalId: "HOSP22P2524503",
    name: "OM HOSPITAL",
    city: null,
    state: null,
    pincode: null,
    address: "PRATAPDEV WARD NO 11, INFRONT OF HATHA GROUND,JAGADALPUR,BASTAR",
    latitude: null,
    longitude: null,
    specialties: ["Burns Management", "General Medicine", "General Surgery", "Neo-natal Care"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "pending",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9827162333",
    facilityType: "Hospital",
    dateOfEstablishment: "17-09-2024",
  },
  {
    hospitalId: "HOSP6P2525796",
    name: "H S MEMORIAL HOSPITAL",
    city: null,
    state: null,
    pincode: null,
    address: "ASSANDH ROAD PANIPAT",
    latitude: null,
    longitude: null,
    specialties: ["General Surgery", "Neo-natal Care", "Orthopaedics", "Paediatric Medical Management"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "pending",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9992839999",
    facilityType: "Hospital",
    dateOfEstablishment: "02-05-2024",
  },
  {
    hospitalId: "HOSP21P110099",
    name: "NEW LIFE HOSPITAL UNIT II",
    city: null,
    state: null,
    pincode: null,
    address: "RADHARANI PARA",
    latitude: null,
    longitude: null,
    specialties: ["Ophthalmology"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "pending",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9437033806",
    facilityType: "Hospital",
    dateOfEstablishment: "01-04-1924",
  },
  {
    hospitalId: "HOSP21P110106",
    name: "MAA TARINI MEDICAL SERVICE POLY CLINIC",
    city: null,
    state: null,
    pincode: null,
    address: "NAKHARA",
    latitude: null,
    longitude: null,
    specialties: ["General Medicine", "General Surgery"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "pending",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "7978931223",
    facilityType: "Hospital",
    dateOfEstablishment: "29-10-2024",
  },
  {
    hospitalId: "HOSP21P110109",
    name: "ALL IS WELL HOSPITAL",
    city: null,
    state: null,
    pincode: null,
    address: "omp square",
    latitude: null,
    longitude: null,
    specialties: [],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "pending",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "7978580730",
    facilityType: "Hospital",
    dateOfEstablishment: "29-10-2024",
  },
  {
    hospitalId: "HOSP21P110110",
    name: "MEERA HOSPITAL",
    city: null,
    state: null,
    pincode: null,
    address: "Chunabhatilane,omp sqr",
    latitude: null,
    longitude: null,
    specialties: [],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "pending",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9438512226",
    facilityType: "Hospital",
    dateOfEstablishment: "29-10-2024",
  },
  {
    hospitalId: "HOSP21P110112",
    name: "RX HEALTH CARE",
    city: null,
    state: null,
    pincode: null,
    address: "PLOT NO-921,KHATA NO-501,UNIT NO-35,JHANJIRIMANGALA,GROUN &FIRST FLOOR,AT-RAJABAGICHA,PO-TELENGABAZAR-PS-BADAMBADI,CUTTACK",
    latitude: null,
    longitude: null,
    specialties: ["General Medicine", "General Surgery", "Obstetrics & Gynaecology", "Paediatric Medical Management"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "pending",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "7735198998",
    facilityType: "Hospital",
    dateOfEstablishment: "03-05-2023",
  },
  {
    hospitalId: "HOSP21P110114",
    name: "AR-HOSPITAL",
    city: null,
    state: null,
    pincode: null,
    address: "AT/PO-BHAIRPUR",
    latitude: null,
    longitude: null,
    specialties: ["General Medicine", "General Surgery", "Obstetrics & Gynaecology", "Otorhinolaryngology (ENT)"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "pending",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9437268742",
    facilityType: "Hospital",
    dateOfEstablishment: "29-10-2024",
  },
  {
    hospitalId: "HOSP3P26100096",
    name: "BMC Superspeciality Hospital",
    city: null,
    state: null,
    pincode: null,
    address: "handiaya road barnala",
    latitude: null,
    longitude: null,
    specialties: ["Cardiology", "Cardio-Thoracic & Vascular Surgery", "General Medicine", "General Surgery"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "pending",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "8007698887",
    facilityType: "Hospital",
    dateOfEstablishment: "01-01-2024",
  },
  {
    hospitalId: "HOSP3P26101981",
    name: "GLOBAL  DIAGNOSTIC CENTER AND NURSING HOME",
    city: null,
    state: null,
    pincode: null,
    address: "oppisite civil hospital mlk",
    latitude: null,
    longitude: null,
    specialties: ["General Surgery", "Orthopaedics", "Plastic & Reconstructive Surgery", "Urology"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "pending",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9876718829",
    facilityType: "Hospital",
    dateOfEstablishment: "07-03-2024",
  },
  {
    hospitalId: "HOSP3P25102315",
    name: "GURU NANAK CARDIAC CARE",
    city: null,
    state: null,
    pincode: null,
    address: "FARDIKOT",
    latitude: null,
    longitude: null,
    specialties: ["Cardiology", "General Medicine"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "pending",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9877829041",
    facilityType: "Hospital",
    dateOfEstablishment: "26-05-2025",
  },
  {
    hospitalId: "HOSP3P25103355",
    name: "ALPHA MULTISPECIALITY HOSPITAL",
    city: null,
    state: null,
    pincode: null,
    address: "mcleod road,rani ka bagh",
    latitude: null,
    longitude: null,
    specialties: ["General Medicine", "General Surgery", "Orthopaedics", "Urology"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "pending",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9988461002",
    facilityType: "Hospital",
    dateOfEstablishment: "18-06-2023",
  },
  {
    hospitalId: "HOSP3P26103442",
    name: "Hakim Kishori Lal Hospital Pvt Ltd Ghs",
    city: null,
    state: null,
    pincode: null,
    address: "Adarsh Nagar Guru Har Sahai",
    latitude: null,
    longitude: null,
    specialties: [],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "pending",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9814641432",
    facilityType: "Hospital",
    dateOfEstablishment: "16-05-1996",
  },
  {
    hospitalId: "HOSP3P25105740",
    name: "ALGON HOSPITAL",
    city: null,
    state: null,
    pincode: null,
    address: "MAJITHA ROAD AMRITSAR",
    latitude: null,
    longitude: null,
    specialties: ["General Medicine", "General Surgery", "Obstetrics & Gynaecology", "Orthopaedics"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "pending",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "8837683032",
    facilityType: "Hospital",
    dateOfEstablishment: "11-11-2024",
  },
  {
    hospitalId: "HOSP3P26106970",
    name: "shankar superspeciality hospital",
    city: null,
    state: null,
    pincode: null,
    address: "60 B Ranbir marg model town patiala",
    latitude: null,
    longitude: null,
    specialties: ["General Medicine", "General Surgery", "Plastic & Reconstructive Surgery", "Urology"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "pending",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9814962641",
    facilityType: "Hospital",
    dateOfEstablishment: "21-01-2025",
  },
  {
    hospitalId: "HOSP3P26107024",
    name: "EMC SUPER SPECIALITY HOSPITAL BATALA",
    city: null,
    state: null,
    pincode: null,
    address: "Jalandhar Road Batala Distt Gurdaspur Punjab",
    latitude: null,
    longitude: null,
    specialties: ["Cardiology", "General Medicine", "General Surgery", "Neurosurgery"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "pending",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "8054863500",
    facilityType: "Hospital",
    dateOfEstablishment: "16-04-2024",
  },
  {
    hospitalId: "HOSP3P25108933",
    name: "SKSANJEEV MULTISPECIALITY HOSPITAL",
    city: null,
    state: null,
    pincode: null,
    address: "G.T ROAD BHOGPUR JALANDAR",
    latitude: null,
    longitude: null,
    specialties: ["Cardiology", "General Medicine", "General Surgery", "Neurosurgery"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "pending",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9996626330",
    facilityType: "Hospital",
    dateOfEstablishment: "20-06-2024",
  },
  {
    hospitalId: "HOSP3P26111402",
    name: "MAKKAR HOSPITAL",
    city: null,
    state: null,
    pincode: null,
    address: "379 ,ADARSH NAGAR",
    latitude: null,
    longitude: null,
    specialties: ["General Medicine", "General Surgery", "Obstetrics & Gynaecology"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "pending",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9357201790",
    facilityType: "Hospital",
    dateOfEstablishment: "01-04-1995",
  },
  {
    hospitalId: "HOSP3G26155407",
    name: "CHC KAUHRIAN",
    city: null,
    state: null,
    pincode: null,
    address: "CHC KAUHRIAN",
    latitude: null,
    longitude: null,
    specialties: ["Emergency Room Packages", "General Medicine", "General Surgery"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9878825720",
    facilityType: "Hospital",
    dateOfEstablishment: null,
  },
  {
    hospitalId: "HOSP3G26191141",
    name: "Tertiary Cancer Care Centre",
    city: null,
    state: null,
    pincode: null,
    address: "Tertiary Cancer Care Centre, Senia Road, Fazilka",
    latitude: null,
    longitude: null,
    specialties: ["General Medicine", "Obstetrics & Gynaecology", "Orthopaedics"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "8198880999",
    facilityType: "Hospital",
    dateOfEstablishment: "18-11-2024",
  },
  {
    hospitalId: "HOSP3G25191477",
    name: "ESIC MEDICAL COLLEGE AND HOSPITAL",
    city: null,
    state: null,
    pincode: null,
    address: "BHARAT NAGAR CHOWNK",
    latitude: null,
    longitude: null,
    specialties: ["General Medicine", "General Surgery", "Obstetrics & Gynaecology", "Ophthalmology"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9711152370",
    facilityType: "Medical College Hospital",
    dateOfEstablishment: "24-02-1952",
  },
  {
    hospitalId: "HOSP3G25246586",
    name: "PUNJAB INSTITUTE OF LIVER AND BILIARY SCIENCES",
    city: null,
    state: null,
    pincode: null,
    address: "Phase 3B-1, Sector-60, SAS Nagar, Mohali, Punjab",
    latitude: null,
    longitude: null,
    specialties: ["General Medicine", "General Surgery", "Medical Oncology", "Surgical Oncology"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9417030923",
    facilityType: "Hospital",
    dateOfEstablishment: "06-09-2023",
  },
  {
    hospitalId: "HOSP3G58215",
    name: "CHC Bajakhana",
    city: null,
    state: null,
    pincode: null,
    address: "CHC Bajakhana",
    latitude: null,
    longitude: null,
    specialties: ["Burns Management", "Cardiology", "Cardio-Thoracic & Vascular Surgery", "Emergency Room Packages"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9592720937",
    facilityType: "Hospital",
    dateOfEstablishment: "06-05-2014",
  },
  {
    hospitalId: "HOSP3G58220",
    name: "CHC Maur",
    city: null,
    state: null,
    pincode: null,
    address: "Maur,Maur",
    latitude: null,
    longitude: null,
    specialties: ["Burns Management", "Cardiology", "Cardio-Thoracic & Vascular Surgery", "Emergency Room Packages"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9463444415",
    facilityType: "Hospital",
    dateOfEstablishment: null,
  },
  {
    hospitalId: "HOSP3G58245",
    name: "CHC Ballianwali",
    city: null,
    state: null,
    pincode: null,
    address: "Ballianwali Civil Hospital",
    latitude: null,
    longitude: null,
    specialties: ["Burns Management", "Cardiology", "Cardio-Thoracic & Vascular Surgery", "Emergency Room Packages"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9779095225",
    facilityType: "Hospital",
    dateOfEstablishment: null,
  },
  {
    hospitalId: "HOSP3G58356",
    name: "CHC Nurpur Bedi",
    city: null,
    state: null,
    pincode: null,
    address: "VILL SINGHPUR, PO NURPUR BEDI",
    latitude: null,
    longitude: null,
    specialties: ["Burns Management", "Cardio-Thoracic & Vascular Surgery", "Emergency Room Packages", "General Medicine"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9501812122",
    facilityType: "Hospital",
    dateOfEstablishment: null,
  },
  {
    hospitalId: "HOSP3G58357",
    name: "SDH ANANDPUR SAHIB",
    city: null,
    state: null,
    pincode: null,
    address: "HOSPITAL ANANDPUR SAHIB",
    latitude: null,
    longitude: null,
    specialties: ["Burns Management", "Cardiology", "Emergency Room Packages", "General Medicine"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "8081340007",
    facilityType: "Hospital",
    dateOfEstablishment: "04-06-1998",
  },
  {
    hospitalId: "HOSP3G58364",
    name: "CHC Morinda",
    city: null,
    state: null,
    pincode: null,
    address: "Near railway phatak Morinda,Morinda",
    latitude: null,
    longitude: null,
    specialties: ["Burns Management", "Cardio-Thoracic & Vascular Surgery", "Emergency Room Packages", "General Medicine"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "6283796329",
    facilityType: "Hospital",
    dateOfEstablishment: "30-10-2018",
  },
  {
    hospitalId: "HOSP3G59614",
    name: "SDH DASUYA",
    city: null,
    state: null,
    pincode: null,
    address: "civil hospital hoshiarpur road dasuya,Civil Hospital Hoshiarpur Road Dasuya",
    latitude: null,
    longitude: null,
    specialties: ["Burns Management", "Cardiology", "Cardio-Thoracic & Vascular Surgery", "Emergency Room Packages"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9915091255",
    facilityType: "Hospital",
    dateOfEstablishment: "01-06-1974",
  },
  {
    hospitalId: "HOSP3G61862",
    name: "CHC Mahilpur",
    city: null,
    state: null,
    pincode: null,
    address: "Mahilpur W.NO. 4,Near Police Station",
    latitude: null,
    longitude: null,
    specialties: ["Burns Management", "Cardiology", "Cardio-Thoracic & Vascular Surgery", "Emergency Room Packages"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9417305719",
    facilityType: "Hospital",
    dateOfEstablishment: "01-06-1994",
  },
  {
    hospitalId: "HOSP3G81040",
    name: "SDH MUKERIAN",
    city: null,
    state: null,
    pincode: null,
    address: "Civil Hospital Mukerian",
    latitude: null,
    longitude: null,
    specialties: ["Burns Management", "Cardio-Thoracic & Vascular Surgery", "Emergency Room Packages", "General Medicine"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "8968837551",
    facilityType: "Hospital",
    dateOfEstablishment: "01-01-1995",
  },
  {
    hospitalId: "HOSP3G81353",
    name: "DH Hoshiarpur",
    city: null,
    state: null,
    pincode: null,
    address: "Mohalla Kamlapur Near Bus standa, Civil hospital, Distt. Hoshiarpur,NEAR BUS STAND",
    latitude: null,
    longitude: null,
    specialties: ["Burns Management", "Cardiology", "Cardio-Thoracic & Vascular Surgery", "Emergency Room Packages"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9815618178",
    facilityType: "Hospital",
    dateOfEstablishment: "01-06-1959",
  },
  {
    hospitalId: "HOSP3G81391",
    name: "CHC Tanda",
    city: null,
    state: null,
    pincode: null,
    address: "Civil Hospital Tanda,Civil Hospital",
    latitude: null,
    longitude: null,
    specialties: ["Burns Management", "Cardiology", "Cardio-Thoracic & Vascular Surgery", "Emergency Room Packages"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9417146570",
    facilityType: "Hospital",
    dateOfEstablishment: "07-07-2001",
  },
  {
    hospitalId: "HOSP3G88411",
    name: "CHC MAND BHANDER",
    city: null,
    state: null,
    pincode: null,
    address: "VILL. PANDHER ,NEAR PETROL PUMP MAKKOWAL ROAD DASUYA",
    latitude: null,
    longitude: null,
    specialties: ["Burns Management", "Cardio-Thoracic & Vascular Surgery", "Emergency Room Packages", "General Medicine"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9417286069",
    facilityType: "Hospital",
    dateOfEstablishment: "01-01-1979",
  },
  {
    hospitalId: "HOSP3G89881",
    name: "CHC BUDHABAR",
    city: null,
    state: null,
    pincode: null,
    address: "CHC Budhabar,near punjab national bank",
    latitude: null,
    longitude: null,
    specialties: ["Burns Management", "Cardiology", "Cardio-Thoracic & Vascular Surgery", "Emergency Room Packages"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9872334492",
    facilityType: "Hospital",
    dateOfEstablishment: "09-08-1981",
  },
  {
    hospitalId: "HOSP3G89889",
    name: "CHC Bhunga",
    city: null,
    state: null,
    pincode: null,
    address: "Dasuya-Hoshiarpur Road,Bhunga",
    latitude: null,
    longitude: null,
    specialties: ["Burns Management", "Cardiology", "Cardio-Thoracic & Vascular Surgery", "Emergency Room Packages"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9417757999",
    facilityType: "Hospital",
    dateOfEstablishment: null,
  },
  {
    hospitalId: "HOSP3G90204",
    name: "SDH GARHSHANKAR",
    city: null,
    state: null,
    pincode: null,
    address: "ANANDPUR SAHIB ROAD, GARHSHANKAR",
    latitude: null,
    longitude: null,
    specialties: ["Burns Management", "Cardiology", "Cardio-Thoracic & Vascular Surgery", "Emergency Room Packages"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9815973938",
    facilityType: "Hospital",
    dateOfEstablishment: "01-11-1980",
  },
  {
    hospitalId: "HOSP3G91678",
    name: "CHC Hajipur",
    city: null,
    state: null,
    pincode: null,
    address: "Mukerian,Hazipur",
    latitude: null,
    longitude: null,
    specialties: ["Burns Management", "Cardiology", "Cardio-Thoracic & Vascular Surgery", "Emergency Room Packages"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9872432305",
    facilityType: "Hospital",
    dateOfEstablishment: null,
  },
  {
    hospitalId: "HOSP3P26138250",
    name: "DHAMI NURSING HOME HOSHIARPUR",
    city: null,
    state: null,
    pincode: null,
    address: "DHAMI HOSPITAL NEAR PARBHAT CHOWNK, HOSHIARPUR",
    latitude: null,
    longitude: null,
    specialties: [],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "pending",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9815197135",
    facilityType: "Hospital",
    dateOfEstablishment: "10-01-1999",
  },
  {
    hospitalId: "HOSP3P26150662",
    name: "MATHON APEX HOSPITAL",
    city: null,
    state: null,
    pincode: null,
    address: "QILA ROAD,MUKERIAN",
    latitude: null,
    longitude: null,
    specialties: ["General Surgery", "Urology"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "pending",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9855472371",
    facilityType: "Hospital",
    dateOfEstablishment: "01-08-2019",
  },
  {
    hospitalId: "HOSP3P26283480",
    name: "PARVESH HOSPITAL",
    city: null,
    state: null,
    pincode: null,
    address: "Parvesh hospital,Vpo Bhater Tehsil Mukerian District Hoshiarpur",
    latitude: null,
    longitude: null,
    specialties: ["General Medicine", "General Surgery", "Orthopaedics", "Otorhinolaryngology (ENT)"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "pending",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "8872059008",
    facilityType: "Hospital",
    dateOfEstablishment: "02-08-2024",
  },
  {
    hospitalId: "HOSP3P36398",
    name: "P R K M Modern Hopital",
    city: null,
    state: null,
    pincode: null,
    address: "SUTEHRI ROAD, HOSHAIRPUR,Opp. Govt. College Chowk",
    latitude: null,
    longitude: null,
    specialties: ["General Medicine", "General Surgery", "Orthopaedics", "Urology"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "pending",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9814074275",
    facilityType: "Hospital",
    dateOfEstablishment: "02-01-2002",
  },
  {
    hospitalId: "HOSP3P98811",
    name: "NARADHOSPITAL MULTISPECIALITY & TRAUMA CENTRE",
    city: null,
    state: null,
    pincode: null,
    address: "FATEHGARH ROAD, NEAR SESSION CHOWK, HOSHIARPUR",
    latitude: null,
    longitude: null,
    specialties: ["Cardiology", "General Medicine", "Neurosurgery", "Orthopaedics"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "pending",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9417665100",
    facilityType: "Hospital",
    dateOfEstablishment: "23-08-2008",
  },
  {
    hospitalId: "HOSP3P102822",
    name: "Super Specialities",
    city: null,
    state: null,
    pincode: null,
    address: "g.t Road ,near petrol pump",
    latitude: null,
    longitude: null,
    specialties: [],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "pending",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9814218688",
    facilityType: "Hospital",
    dateOfEstablishment: "01-01-1993",
  },
  {
    hospitalId: "HOSP3P130925",
    name: "Jhanjee Hospital",
    city: null,
    state: null,
    pincode: null,
    address: "Adarsh Nagar",
    latitude: null,
    longitude: null,
    specialties: ["General Surgery", "Urology"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "pending",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9417140786",
    facilityType: "Hospital",
    dateOfEstablishment: "01-04-1999",
  },
  {
    hospitalId: "HOSP3P184232",
    name: "CITY HOSPITAL",
    city: null,
    state: null,
    pincode: null,
    address: "NEAR LIC OFFICE GT ROAD GURDASPUR,GURDASPUR",
    latitude: null,
    longitude: null,
    specialties: ["General Medicine", "General Surgery", "Orthopaedics", "Urology"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "pending",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9855092828",
    facilityType: "Hospital",
    dateOfEstablishment: "22-09-2022",
  },
  {
    hospitalId: "HOSP3P26141563",
    name: "R R M CENTRAL HOSPITAL",
    city: null,
    state: null,
    pincode: null,
    address: "ST No 3 central town Hoshiarpur,ST No 3 Central Town Hoshiarpur",
    latitude: null,
    longitude: null,
    specialties: ["Obstetrics & Gynaecology"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "pending",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9872561900",
    facilityType: "Hospital",
    dateOfEstablishment: "04-04-2011",
  },
  {
    hospitalId: "HOSP23G25100014",
    name: "Primary Health Center Baijagwada",
    city: null,
    state: null,
    pincode: null,
    address: "Baijagwada",
    latitude: null,
    longitude: null,
    specialties: ["General Medicine"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9575412706",
    facilityType: "Hospital",
    dateOfEstablishment: null,
  },
  {
    hospitalId: "HOSP27G25100017",
    name: "Nandgaon",
    city: null,
    state: null,
    pincode: null,
    address: "Ap/Post Nandgaon Tal/Dist Satara",
    latitude: null,
    longitude: null,
    specialties: ["Emergency Room Packages", "General Medicine", "Obstetrics & Gynaecology"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "8830521058",
    facilityType: "Hospital",
    dateOfEstablishment: null,
  },
  {
    hospitalId: "HOSP5G25100090",
    name: "PHC Type A Pathlidhar",
    city: null,
    state: null,
    pincode: null,
    address: "Government Health Center, Pathali Dhar, Rudraprayag",
    latitude: null,
    longitude: null,
    specialties: ["General Medicine"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9027919755",
    facilityType: "Hospital",
    dateOfEstablishment: "20-09-2025",
  },
  {
    hospitalId: "HOSP27G26100294",
    name: "Kadgaon Gadhinglaj",
    city: null,
    state: null,
    pincode: null,
    address: "near primary school ,kadgaon ,near Primary School ,Kadgaon",
    latitude: null,
    longitude: null,
    specialties: ["Emergency Room Packages", "General Medicine", "General Surgery", "Neo-natal Care"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9422509147",
    facilityType: "Hospital",
    dateOfEstablishment: null,
  },
  {
    hospitalId: "HOSP23G25100351",
    name: "phc bijuri",
    city: null,
    state: null,
    pincode: null,
    address: "phc bijuri",
    latitude: null,
    longitude: null,
    specialties: ["General Medicine", "Obstetrics & Gynaecology"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "8982114463",
    facilityType: "Hospital",
    dateOfEstablishment: null,
  },
  {
    hospitalId: "HOSP23G26100452",
    name: "PHC RAMNAGAR",
    city: null,
    state: null,
    pincode: null,
    address: "GRAM RAMNAGAR",
    latitude: null,
    longitude: null,
    specialties: ["General Medicine"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9993675262",
    facilityType: "Daycare Centre",
    dateOfEstablishment: null,
  },
  {
    hospitalId: "HOSP23G25100718",
    name: "CHC KARANJA",
    city: null,
    state: null,
    pincode: null,
    address: "WARD NO 11 PARSODI POST KULPA TAH LANJI BALAGHAT",
    latitude: null,
    longitude: null,
    specialties: ["General Medicine", "Obstetrics & Gynaecology"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9893208837",
    facilityType: "Hospital",
    dateOfEstablishment: null,
  },
  {
    hospitalId: "HOSP5G25100844",
    name: "PHC Type A Ghangarkhal",
    city: null,
    state: null,
    pincode: null,
    address: "Government Health Center, Ghengarkhal, Jakholi, Rudraorayag",
    latitude: null,
    longitude: null,
    specialties: ["General Medicine"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "6396198939",
    facilityType: "Hospital",
    dateOfEstablishment: null,
  },
  {
    hospitalId: "HOSP27G26101062",
    name: "PHC Shibla",
    city: null,
    state: null,
    pincode: null,
    address: "At.Po.Shibla Ta.Zarijamani Dist.Yavatmal",
    latitude: null,
    longitude: null,
    specialties: ["General Medicine"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "9422924096",
    facilityType: "Hospital",
    dateOfEstablishment: "20-03-1982",
  },
  {
    hospitalId: "HOSP27G26101106",
    name: "Devle",
    city: null,
    state: null,
    pincode: null,
    address: "devale,devale",
    latitude: null,
    longitude: null,
    specialties: ["General Medicine"],
    procedures: [],
    costMin: null,
    costMax: null,
    currency: "INR",
    facilities: [],
    accreditation: [],
    pmjayEmpanelled: true,
    annualProcedureVolume: null,
    outcomeMetric: null,
    icuBeds: null,
    sourceType: "official",
    verificationStatus: "verified",
    sourceUrl: "https://hem.nha.gov.in/search",
    lastVerified: null,
    lastUpdated: "2026-09-22",
    dataStatus: "nha_pmjay_data",
    conditionTag: null,
    reviewStatus: "approved",
    phone: "8862069180",
    facilityType: "Hospital",
    dateOfEstablishment: null,
  }
];
