import {
  durationLabel,
  SEVERITY_LABEL,
  type TriageInput,
  type TriageResult,
} from "./types";
import { getCluster } from "./clusters";

/**
 * Builds the clinical intake summary a patient hands to their doctor.
 *
 * This is the "organized clinical intake preparation" deliverable: a structured,
 * copyable, printable record assembled entirely from data the patient already
 * supplied or that a clinician-grade rule engine verified. Nothing here is
 * model-invented, so nothing here can be a hallucination.
 */

const INTENSITY_WORD = {
  mild: "Mild",
  moderate: "Moderate",
  severe: "Severe",
} as const;

const SEVERITY_HEADLINE = {
  emergency: "EMERGENCY — immediate care needed",
  urgent: "URGENT — should be seen today",
  routine: "ROUTINE — appointment needed",
  self_care: "SELF-CARE — monitor, with safety net",
} as const;

function formatDate(): string {
  return new Date().toLocaleDateString(undefined, {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

/** Plain-text version, used for the copy-to-clipboard action. */
export function buildIntakeSummaryText(
  input: TriageInput,
  result: TriageResult
): string {
  const lines: string[] = [];
  const rule = "-".repeat(58);

  lines.push("CURANAV — CLINICAL INTAKE SUMMARY");
  lines.push(`Prepared: ${formatDate()}`);
  lines.push(rule);

  lines.push("");
  lines.push("CHIEF COMPLAINT");
  lines.push(result.normalizedComplaint || input.symptoms);
  lines.push("");

  lines.push("SYMPTOM PROFILE");
  lines.push(`  Duration        : ${durationLabel(input.duration)}`);
  lines.push(`  Intensity       : ${INTENSITY_WORD[input.intensity]}`);
  lines.push(`  Symptom areas   : ${result.clusters.length > 0
    ? result.clusters.map((id) => getCluster(id)?.label ?? id).join(", ")
    : "Not classified"}`);
  if (result.associatedSymptoms.length > 0) {
    lines.push(`  Also reported   : ${result.associatedSymptoms.join(", ")}`);
  }
  lines.push("");

  lines.push("TRIAGE SUMMARY");
  lines.push(`  Level           : ${SEVERITY_HEADLINE[result.severity]}`);
  lines.push(`  Advised level   : ${SEVERITY_LABEL[result.severity]}`);
  for (const reason of result.severityReasons) {
    lines.push(`    - ${reason}`);
  }
  lines.push("");

  if (result.redFlags.length > 0) {
    lines.push("RED FLAGS SCREENED (POSITIVE)");
    for (const flag of result.redFlags) {
      lines.push(`  [+] ${flag.label}`);
      lines.push(`      ${flag.category} — ${flag.rationale}`);
    }
    lines.push("");
  } else {
    lines.push("RED FLAGS SCREENED");
    lines.push("  No red-flag symptoms detected.");
    lines.push("");
  }

  if (result.suggestedSpecialties.length > 0) {
    lines.push("SUGGESTED DEPARTMENT");
    lines.push(`  ${result.suggestedSpecialties.join(", ")}`);
    lines.push("");
  }

  lines.push("HISTORY");
  lines.push(
    `  Age group       : ${input.age ?? "Not provided"}`
  );
  lines.push(`  Sex             : ${input.sex ?? "Not provided"}`);
  lines.push(`  Pregnancy       : ${input.isPregnant ? "Yes" : "No"}`);
  lines.push(
    `  Conditions      : ${input.existingConditions.trim() || "None reported"}`
  );
  lines.push(
    `  Medications     : ${input.currentMedications.trim() || "None reported"}`
  );
  lines.push("");

  if (input.reportedFlags.length > 0) {
    lines.push("PATIENT-REPORTED WARNING SIGNS");
    for (const id of input.reportedFlags) {
      lines.push(`  [x] ${id}`);
    }
    lines.push("");
  }

  if (result.care.length > 0) {
    lines.push("SELF-CARE ALREADY SUGGESTED");
    for (const entry of result.care) {
      lines.push(`  - ${entry.title}`);
    }
    lines.push("");
  }

  if (result.followupQuestions.length > 0) {
    lines.push("QUESTIONS TO DISCUSS WITH THE DOCTOR");
    result.followupQuestions.forEach((q, i) => {
      lines.push(`  ${i + 1}. ${q}`);
    });
    lines.push("");
  }

  lines.push(rule);
  lines.push(
    "This summary was generated by an automated intake aid. It is not a"
  );
  lines.push(
    "diagnosis and has not been reviewed by a clinician. Nothing here should"
  );
  lines.push("replace the doctor's own assessment.");

  return lines.join("\n");
}

/** Row/label pairs for structured rendering in the UI. */
export function buildIntakeSummaryRows(
  input: TriageInput,
  result: TriageResult
): Array<{ label: string; value: string }> {
  const rows: Array<{ label: string; value: string }> = [
    { label: "Prepared", value: formatDate() },
    { label: "Chief complaint", value: result.normalizedComplaint || input.symptoms },
    { label: "Duration", value: durationLabel(input.duration) },
    { label: "Intensity", value: INTENSITY_WORD[input.intensity] },
    {
      label: "Symptom areas",
      value:
        result.clusters.length > 0
          ? result.clusters.map((id) => getCluster(id)?.label ?? id).join(", ")
          : "Not classified",
    },
  ];

  if (result.associatedSymptoms.length > 0) {
    rows.push({ label: "Also reported", value: result.associatedSymptoms.join(", ") });
  }

  rows.push({ label: "Triage level", value: SEVERITY_HEADLINE[result.severity] });

  if (result.suggestedSpecialties.length > 0) {
    rows.push({ label: "Suggested department", value: result.suggestedSpecialties.join(", ") });
  }

  rows.push({ label: "Age group", value: input.age ?? "Not provided" });
  rows.push({ label: "Sex", value: input.sex ?? "Not provided" });
  rows.push({ label: "Pregnancy", value: input.isPregnant ? "Yes" : "No" });
  rows.push({
    label: "Existing conditions",
    value: input.existingConditions.trim() || "None reported",
  });
  rows.push({
    label: "Current medications",
    value: input.currentMedications.trim() || "None reported",
  });

  return rows;
}
